---
- name: Copy backend dir
  become: yes
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Copy dist directory
  become: yes
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend/artifact.tar.gz
    force: yes

# - name: Copy .env file
#   become: yes
#   copy:
#     src: .env
#     dest: /home/ubuntu/backend/.env
#     owner: "{{ ansible_user }}"
#     group: "{{ ansible_user }}"

- name: Deploy Server
  become: yes
  shell: |
    args:
      executable: /bin/bash
    pwd
    cd /home/ubuntu/backend
    echo It works > testit.txt
    tar -xvf artifact.tar.gz
    npm install
    pm2 stop default
    pm2 start npm --no-automation --name "backend" -- run start
