route:
  group_by: [Alertname]
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: ALERT_RECEIVER_EMAIL
    from: ALERT_SENDER_EMAIL
    smarthost: smtp.gmail.com:587
    auth_username: ALERT_SENDER_EMAIL
    auth_identity: ALERT_SENDER_EMAIL
    auth_password: ALERT_EMAIL_PASSWORD
